EJERCICIOS DE INDEXACION EN PANDAS

Para seguir prácticando con Pandas os planteamos los siguientes ejercicios: 

1- Abre el fichero de `rating-and-performance` con el método que sea más correcto. Además muestra las 5 primeras filas del *DataFrame*.

In [11]:
import pandas as pd

df = pd.read_csv("rating-and-performance.csv", index_col=[0])

df

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
index,,,,,,,,,,,,,,,,,,,,,
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14,EUR,100,0,3.76,54,26.0,...,568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,8.00,22,EUR,20000,1,3.45,6135,2269.0,...,17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,2020 New Arrival Women Spring and Summer Beach...,8.00,43,EUR,100,0,3.57,14,5.0,...,295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
3,Hot Summer Cool T-shirt pour les femmes Mode T...,Hot Summer Cool T Shirt for Women Fashion Tops...,8.00,8,EUR,5000,1,4.03,579,295.0,...,23832,4.020435,58cfdefdacb37b556efdff7c,0,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08
4,Femmes Shorts d'été à lacets taille élastique ...,Women Summer Shorts Lace Up Elastic Waistband ...,2.72,3,EUR,100,1,3.10,20,6.0,...,14482,4.001588,5ab3b592c3911a095ad5dadb,0,NaN,https://www.wish.com/c/5ebf5819ebac372b070b0e70,https://contestimg.wish.com/api/webimage/5ebf5...,5ebf5819ebac372b070b0e70,summer,2020-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1568,Nouvelle Mode Femmes Bohême Pissenlit Imprimer...,New Fashion Women Bohemia Dandelion Print Tee ...,6.00,9,EUR,10000,1,4.08,1367,722.0,...,5316,4.224605,5b507899ab577736508a0782,0,NaN,https://www.wish.com/c/5d5fadc99febd9356cbc52ee,https://contestimg.wish.com/api/webimage/5d5fa...,5d5fadc99febd9356cbc52ee,summer,2020-08
1569,10 couleurs femmes shorts d'été lacent ceintur...,10 Color Women Summer Shorts Lace Up Elastic W...,2.00,56,EUR,100,1,3.07,28,11.0,...,4435,3.696054,54d83b6b6b8a771e478558de,0,NaN,https://www.wish.com/c/5eccd22b4497b86fd48f16b4,https://contestimg.wish.com/api/webimage/5eccd...,5eccd22b4497b86fd48f16b4,summer,2020-08
1570,Nouveautés Hommes Siwmwear Beach-Shorts Hommes...,New Men Siwmwear Beach-Shorts Men Summer Quick...,5.00,19,EUR,100,0,3.71,59,24.0,...,210,3.961905,5b42da1bf64320209fc8da69,0,NaN,https://www.wish.com/c/5e74be96034d613d42b52dfe,https://contestimg.wish.com/api/webimage/5e74b...,5e74be96034d613d42b52dfe,summer,2020-08
1571,Mode femmes d'été sans manches robes col en V ...,Fashion Women Summer Sleeveless Dresses V Neck...,13.00,11,EUR,100,0,2.50,2,0.0,...,31,3.774194,5d56b32c40defd78043d5af9,0,NaN,https://www.wish.com/c/5eda07ab0e295c2097c36590,https://contestimg.wish.com/api/webimage/5eda0...,5eda07ab0e295c2097c36590,summer,2020-08
1572,Pantalon de yoga pour femmes à la mode Slim Fi...,Fashion Women Yoga Pants Slim Fit Fitness Runn...,7.00,6,EUR,100,1,4.07,14,8.0,...,7023,4.235939,5a409cf87b584e7951b2e25f,0,NaN,https://www.wish.com/c/5e857321f53c3d2d8f25e7ed,https://contestimg.wish.com/api/webimage/5e857...,5e857321f53c3d2d8f25e7ed,summer,2020-08

2- Pongamos en práctica el `loc` e `iloc`:

Usando el `loc`: 

- Extraed todas las filas de la columna "price". ¿De qué tipo es el resultado obtenido?

In [52]:
resultado1 = df.loc[:, "price"]

print(resultado1)

print("\n"f"El resultado es de tipo:", type(resultado1))

index
0       16.00
1        8.00
2        8.00
3        8.00
4        2.72
        ...
1568     6.00
1569     2.00
1570     5.00
1571    13.00
1572     7.00
Name: price, Length: 1573, dtype: float64

El resultado es de tipo: <class 'pandas.core.series.Series'>

- Extraed todas las filas de las columnas "price" y "retail_price". ¿De qué tipo es el resultado obtenido?

In [53]:
resultado2 = df.loc[:, ("price", "retail_price")]

print(resultado2)

print("\n"f"El resultado es de tipo:", type(resultado2))

       price  retail_price
index
0      16.00            14
1       8.00            22
2       8.00            43
3       8.00             8
4       2.72             3
...      ...           ...
1568    6.00             9
1569    2.00            56
1570    5.00            19
1571   13.00            11
1572    7.00             6

[1573 rows x 2 columns]

El resultado es de tipo: <class 'pandas.core.frame.DataFrame'>

- Extraed las filas pares, de las columnas "rating", "rating_count", "rating_five_count", "rating_four_count", "rating_three_count", "rating_two_count", "rating_one_count".

In [54]:
df.loc[::2, ("rating", "rating_count", "rating_five_count", "rating_four_count", "rating_three_count", "rating_two_count", "rating_one_count")]

,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count
index,,,,,,,
0,3.76,54,26.0,8.0,10.0,1.0,9.0
2,3.57,14,5.0,4.0,2.0,0.0,3.0
4,3.10,20,6.0,4.0,2.0,2.0,6.0
6,3.84,6742,3172.0,1352.0,971.0,490.0,757.0
8,3.47,15,6.0,2.0,3.0,1.0,3.0
...,...,...,...,...,...,...,...
1564,3.38,414,156.0,58.0,72.0,45.0,83.0
1566,3.54,28,7.0,11.0,4.0,2.0,4.0
1568,4.08,1367,722.0,293.0,185.0,77.0,90.0
1570,3.71,59,24.0,15.0,8.0,3.0,9.0
1572,4.07,14,8.0,3.0,1.0,0.0,2.0

- Extraed las las filas cuyo precio sea mayor que 10 y sus unidades vendidas ("units_sold") sea mayor que 5000.

In [78]:
resultado3 = df[(df["price"] > 10) & (df["units_sold"] > 5000)]

resultado3

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
index,,,,,,,,,,,,,,,,,,,,,
16,Nouvelle mode d'été pour femmes Robe sans manc...,New Summer Women's Fashion Sleeveless Polka Do...,11.0,10,EUR,10000,0,3.72,2058,840.0,...,6302,3.958426,5b8beef49996c87b299cdbec,0,NaN,https://www.wish.com/c/5cd3e795ebe403118bbc0f89,https://contestimg.wish.com/api/webimage/5cd3e...,5cd3e795ebe403118bbc0f89,summer,2020-08
77,Nouveau Mode Femmes Casual Shorts Costume Été ...,New Fashion Women Casual Shorts Suit Summer Ti...,11.0,10,EUR,10000,0,4.24,1045,644.0,...,9200,4.289674,583e7f658108913bced6f8cf,0,NaN,https://www.wish.com/c/5b29e5b5080ea2661b2287f6,https://contestimg.wish.com/api/webimage/5b29e...,5b29e5b5080ea2661b2287f6,summer,2020-08
89,NOUVELLE Robe d'été sans manches imprimée à fl...,NEW Women Summer Floral Printed Sleeveless Dr...,11.0,10,EUR,20000,1,4.07,3070,1635.0,...,12974,3.965701,5a7b23a69bda4e3d375e7b3f,0,NaN,https://www.wish.com/c/5cf5e44b3c8b9e101a5db52c,https://contestimg.wish.com/api/webimage/5cf5e...,5cf5e44b3c8b9e101a5db52c,summer,2020-08
109,Casual femmes ras du cou à manches courtes feu...,Casual Women Crew Neck Short Sleeve Leaf Print...,11.0,10,EUR,10000,0,3.77,1694,725.0,...,13946,4.000143,559d33adc605853731afbf10,0,NaN,https://www.wish.com/c/5c78151c27202a28a75752b7,https://contestimg.wish.com/api/webimage/5c781...,5c78151c27202a28a75752b7,summer,2020-08
111,Femmes classiques dos nu en dentelle évider li...,Classic Women Backless Lace Hollow Out Halter ...,14.0,12,EUR,10000,0,3.93,2946,1427.0,...,32858,3.885538,57baf75f63834218e305e4f4,0,NaN,https://www.wish.com/c/5acb7ae3a69e662bb0133546,https://contestimg.wish.com/api/webimage/5acb7...,5acb7ae3a69e662bb0133546,summer,2020-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1533,Tenues deux pièces Totem Print Femmes Sexy Dos...,Two Piece Outfits Totem Print Women Sexy Backl...,16.0,14,EUR,10000,0,3.74,3079,1311.0,...,78616,4.310433,5705e40cfda6252c1a9db062,0,NaN,https://www.wish.com/c/5919b96486a1694f4fbcfa12,https://contestimg.wish.com/api/webimage/5919b...,5919b96486a1694f4fbcfa12,summer,2020-08
1534,Femmes Chemisier d'été Chemise Sexy Floral Che...,Womens Summer Blouse Sexy Floral Shirt Loose K...,11.0,18,EUR,20000,1,4.14,5759,3125.0,...,320031,4.218866,5357bcf2bb72c5504882e889,1,https://s3-us-west-1.amazonaws.com/sweeper-pro...,https://www.wish.com/c/572981a997dc5f5d3c5f0651,https://contestimg.wish.com/api/webimage/57298...,572981a997dc5f5d3c5f0651,summer,2020-08
1537,Plus la taille XS-7XL été femmes mode col rond...,Plus Size XS-7XL Summer Women Fashion Round Ne...,11.0,12,EUR,10000,0,3.96,666,360.0,...,9325,4.122466,5937930e188f3d1bd209896d,0,NaN,https://www.wish.com/c/5c3befd857ceb9569c5dbb8d,https://contestimg.wish.com/api/webimage/5c3be...,5c3befd857ceb9569c5dbb8d,summer,2020-08
1548,Robe d'été surdimensionnée pour dames Robe lon...,Oversize Women Summer Evening Cocktail Party B...,12.0,87,EUR,10000,0,4.11,2404,1324.0,...,90105,4.201298,58131ddf6f55296033923a7c,1,https://s3-us-west-1.amazonaws.com/sweeper-pro...,https://www.wish.com/c/5840d0503d6ce66bf4ff84e0,https://contestimg.wish.com/api/webimage/5840d...,5840d0503d6ce66bf4ff84e0,summer,2020-08
1558,Mode d'été pour dames Jumpsuit sans manches im...,Summer Fashion Women's Jumpsuit Floral Print S...,13.0,11,EUR,10000,0,4.12,2901,1573.0,...,14502,4.147842,56c3c5d830d9795c3bad3124,1,https://s3-us-west-1.amazonaws.com/sweeper-pro...,https://www.wish.com/c/5a6ac97e5983516f0f0dbf85,https://contestimg.wish.com/api/webimage/5a6ac...,5a6ac97e5983516f0f0dbf85,summer,2020-08

Usando el `iloc` (sacaremos los mismos resultados que con el loc):

- Extraed todas las filas de la columna "price".

In [61]:
df.iloc[:, 2]

index
0       16.00
1        8.00
2        8.00
3        8.00
4        2.72
        ...
1568     6.00
1569     2.00
1570     5.00
1571    13.00
1572     7.00
Name: price, Length: 1573, dtype: float64

- Extraed todas las filas de las columnas "price" y "retail_price".

In [75]:
df.iloc[:, [2, 3]]

       price  retail_price
index
0      16.00            14
1       8.00            22
2       8.00            43
3       8.00             8
4       2.72             3
...      ...           ...
1568    6.00             9
1569    2.00            56
1570    5.00            19
1571   13.00            11
1572    7.00             6

[1573 rows x 2 columns]

- Extraed las filas pares, de las columnas "rating", "rating_count", "rating_five_count", "rating_four_count", "rating_three_count", "rating_two_count", "rating_one_count".

In [76]:
df.iloc[::2, [7, 8, 9, 10, 11, 12, 13]]

,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count
index,,,,,,,
0,3.76,54,26.0,8.0,10.0,1.0,9.0
2,3.57,14,5.0,4.0,2.0,0.0,3.0
4,3.10,20,6.0,4.0,2.0,2.0,6.0
6,3.84,6742,3172.0,1352.0,971.0,490.0,757.0
8,3.47,15,6.0,2.0,3.0,1.0,3.0
...,...,...,...,...,...,...,...
1564,3.38,414,156.0,58.0,72.0,45.0,83.0
1566,3.54,28,7.0,11.0,4.0,2.0,4.0
1568,4.08,1367,722.0,293.0,185.0,77.0,90.0
1570,3.71,59,24.0,15.0,8.0,3.0,9.0
1572,4.07,14,8.0,3.0,1.0,0.0,2.0